project_id = "vineme2"

[analytics]
enabled = false

[auth]
enable_signup = true

[auth.sms]
enable_signup = true

[auth.sms.twilio]
enabled = true
account_sid = "fake_sid"
message_service_sid = "fake_service_sid"
auth_token = "fake_token"

[auth.sms.test_otp]
# Map fake phone numbers to fixed OTPs
"447712345678" = "123456"
"447712345679" = "123456"

[functions.create-referred-user]
enabled = true
entrypoint = "./functions/create-referred-user/index.ts"
import_map = "./functions/create-referred-user/deno.json"

[functions.delete-auth-user]
enabled = true
entrypoint = "./functions/delete-auth-user/index.ts"
import_map = "./functions/delete-auth-user/deno.json"

[functions.notify-missing-service]
enabled = true
entrypoint = "./functions/notify-missing-service/index.ts"
import_map = "./functions/notify-missing-service/deno.json"

[functions.push-notify-2]
enabled = true
entrypoint = "./functions/push-notify/index.ts"
import_map = "./functions/push-notify/deno.json"
